updating Installation docs
python35u-pip doesn't work on fresh centos 7 and centos 8. ( pip is not installed for some reason )
even if python3-pip installed instead,
installation of inginious will return this error 

     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

which needs python3-devel to work.
I have also updated some web conf after testing on centos 8 and 7. (lighttpd)
however the documentation is missing some lighttpd permissions on some folders like /var/run/lighttpd and logs .. 
I didn't add those because any sys admin will figure them out easily.